/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('model/keyCard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.264, 0.64, 0.631]}
        rotation={[0.117, 0.493, 1.491]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clamp.geometry}
        material={materials.metal}
        position={[-0.261, 0.697, 0.637]}
        rotation={[-0.177, -1.143, -0.162]}
        scale={0.188}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clip.geometry}
        material={materials.metal}
        position={[-0.26, 0.717, 0.638]}
        scale={0.145}
      />
    </group>
  )
}

useGLTF.preload('/keyCard.glb')
